[package]
name = "hash-benchmark-cw"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = "0.5.1"
gost94 = "0.10.4"
hex = "0.4.3"
md5 = "0.7.0"
plotters = "0.3.4"
sha256 = "1.1.3"


[[bench]]
name = "hashing"
harness = false
